### ISSUE TITLE
Code and Learn at Node.js Interactive in Amsterdam

### ISSUE THREAD

**Issue by mikeal** [nodejs/code-and-learn#56]
So, I'd like to resurrect this event to run either before or after the Node.js Interactive events in Amsterdam and Austin.

We need to figure out what this will look like so that we can budget it correctly.

As a reminder, this program was intended as a series of workshops for getting people working _on_ Node.js itself. The goal was that by the end of the workshop they would have a PR open, or be close to it.

We need to put together a list of subjects, people that can properly mentor the subject, and if those people need their travel covered we need to know where they are coming from. Also, for each subject and mentor allocation we need to figure out the maximum size of the attendees.

/cc @dshaw @ashleywilliams @hackygolucky @Fishrock123

**Comment by MylesBorins** [comment]
I'd be up for helping with this, obviously dependent on me attending the events

**Comment by bnoordhuis** [comment]
Amsterdam is my home turf (after a fashion) so I'll volunteer.  I request remuneration only for the train ticket but I do tend to travel 1st class exclusively so there's that.

**Comment by iancrowther** [comment]
happy to chip in

**Comment by mikeal** [comment]
We really need someone to step up to lead this effort at Amsterdam and Austin (doesn't need to be the same person each time).

**Comment by jasnell** [comment]
I can help as a mentor on site. Going to be fairly busy I think so I don't want to overcommit as 'lead'

**Comment by MylesBorins** [comment]
@mikeal would this be running during the collaborator summit? Do we have resources to offer individuals, potentially with a focus on under represented groups, continued support after a code and learn?

I think it might be particularly interesting to pair current collaborators with new collaborators. It might also be great if we can offer some sort of scholarship to individuals in need so that they can focus a continued effort on getting involved.

**Comment by Fishrock123** [comment]
Which day is this at in Amsterdam?

I _may_ be able to help but I definitely don't want to lead it.

**Comment by bnoordhuis** [comment]
I can lead but it depends on what day it is.  (EDIT: In Amsterdam.)

**Comment by mikeal** [comment]
Morning of the 17th.

**Comment by addaleax** [comment]
I’ll definitely want to be there and can probably also invest some time into it beforehand.

**Comment by bnoordhuis** [comment]
How morning is morning?  17th works for me but I need to drive up from Groningen.  I can be there around 11 am.

**Comment by addaleax** [comment]
9:00 – 12:00 (http://events.linuxfoundation.org/events/node-interactive-europe/program/agenda)

**Comment by bnoordhuis** [comment]
Thanks, that page was still blank last I checked. :-)

I don't think I'll be able to make 9 am, I'd have to leave before 6 am.

**Comment by mikeal** [comment]
Heya, do you need anything from the events team?

**Comment by Fishrock123** [comment]
I won't be there fwiw.

**Comment by bnoordhuis** [comment]
So who is going to lead?

**Comment by addaleax** [comment]
If nobody else is available, I can try to, even as a newbie… I’d definitely want to talk with people who have done this before in that case

**Comment by MylesBorins** [comment]
im up for being involved, let me know what I can do to help

**Comment by bnoordhuis** [comment]
IRC or email?  Don't worry, the biggest thing is to have some 'good first contribution' issues stacked up, everything else flows from there (after walking people through how to build first.)

**Comment by addaleax** [comment]
hm, how about in IRC in an hour (I’m busy until then), maybe with @TheAlphaNerd too?

**Comment by jasnell** [comment]
I will be there also and can definitely help in any way that I can but I'm more than happy for @addaleax or others to take the lead if they'd like.

**Comment by bnoordhuis** [comment]
I have cheese/bacon pancakes and a Danish krimi to attend to first but I'll hop onto IRC afterwards.  Make it 1.30h from now.

**Comment by addaleax** [comment]
oh, have fun! and yeah, works for me :)

**Comment by MylesBorins** [comment]
ping me when ya’ll are ready, I should be around

**Comment by addaleax** [comment]
oh, yeah, seems I forgot to comment… I should be able to lead this :)

**Comment by addaleax** [comment]
Okay, so from what I’ve gathered by talking to a few people here, the expectations for Code & Learn are a bit diverse, as are the skill levels of attending people. I’ve gathered a few changes that people might up to do, maybe that’s enough (I’ll definitely gather a bit more), but I’m pretty sure that even if not we’re going to be able to provide attendees with things they’re interested in (@saghul even offered to help people with first libuv contributions if they’re interested in that!).

A few things that I think are okay:
- lib/internal/bootstrap_node.js
  - ~~The `NativeModule._cache` can safely be turned into a `Map`!~~
  - `var` -> `const` substitutions
- lib/v8.js, src/node_v8.cc:
  - There are a few fields missing on `HeapStatistics` which have been added in more recent V8 versions:
    - `malloced_memory`
    - `peak_malloced_memory`
    - `does_zap_garbage`
- lib/util.js:
  - _i)_: The SIMD setup can be turned into a loop and the typeof checks can be removed
  - _ii)_: Support for `SharedArrayBuffer` can be added here, too.
  - _iii)_: (Maybe) The catch-all `try` check in `tryStringify()` for circular objects is probably too unspecific
- src/udp_wrap.cc, src/stream_base.cc:
  - The `uv_buf_t bufs_[16]` lines could be `MaybeStackBuffer`s;
- lib/internal/process.js
  - (Maybe) We might want to emit a warning for signals that users shouldn’t listen on (as listed in the docs warning in https://github.com/nodejs/node/pull/8410)?
- lib/internal/lazy_transform.js
  - The default encoding here should be configurable and default to `crypto.DEFAULT_ENCODING`, not `latin1`?. This seems to kind of have been forgotten in https://github.com/nodejs/node/pull/5522 – It would be a `semver-major` change, but I think this is not going to be contentious.
- edit: https://github.com/nodejs/node/issues/3208

And a few test files that could be cleaned up in NodeTodo/@Trott style:
- ~~test-c-ares.js:~~
  - A lot of `var`s that can be `const`
  - `assert.strictEqual` should be used instead of `assert.equal`
  - Wrap all callbacks that should be called once in `common.mustCall()`
- test-child-process-buffering.js:
  - A lot of `var`s that can be `const`
  - `assert.strictEqual` should be used instead of `assert.equal`
- test-child-process-detached.js
  - A lot of `var`s that can be `const`
  - `assert.notStrictEqual` should be used instead of `assert(… !== …)`
- test-child-process-stdio.js:
  - A lot of `var`s that can be `const`
  - `assert.strictEqual` should be used instead of `assert.equal`, the same goes for `notEqual`
- test-child-process-stdout-flush.js:
  - A lot of `var`s that can be `const`
  - `assert.strictEqual` should be used instead of `assert.equal`, the same goes for `notEqual`
  - Wrap all callbacks that should be called once in `common.mustCall()`

Tomorrow we might get a better picure of how many people would be able and willing to attend (maybe @mikeal could ask a quick question when he mentions Code & Learn during the final notes)?

And @mikeal … not sure whether it makes a difference, but maybe we could add your “It's a workshop for people who want to learn how to contribute to Node.js core.” at the beginning and drop the whole “Concerns have also … need to be distributed geographically” part? I think that should clear up everything sufficiently.

/cc a couple of people who are here: @mhdawson @jasnell @bnoordhuis @saghul @mcollina @mikeal @thealphanerd

**Comment by saghul** [comment]
Great work putting that together @addaleax! FWIW, I tagged some issues as good first contributions to libuv here: https://github.com/libuv/libuv/labels/good-first-contribution So if anyone what's to go for it, I'm happy to help as a mentor.

**Comment by jasnell** [comment]
wow... amazing list! To this I would add that there are a number of issues tagged as `docs-requested` that could be accessible to some participants.

**Comment by sejoker** [comment]
I would like to pickup test cleanup of `test-c-ares.js` from @addaleax proposed list

**Comment by wzoom** [comment]
DONE Working on `test-child-process-detached.js` from the comment above

**Comment by MichaelTSS** [comment]
Working on `test-child-process-buffering` from @addaleax's comment

**Comment by alkiskal** [comment]
Working on `test-child-process-stdout-flush.js` from @addaleax's comment

**Comment by AdriVanHoudt** [comment]
Working on `test-child-process-buffering.js`

**Comment by MichaelTSS** [comment]
@AdriVanHoudt ?

**Comment by pmatzavin** [comment]
Working on test-child-process-stdio.js

**Comment by AdriVanHoudt** [comment]
@MichaelTSS yeah I raised my hand ^^ I have a PR ready but you can take it if you want

**Comment by MichaelTSS** [comment]
@AdriVanHoudt keep your PR I'll do something else

**Comment by AdriVanHoudt** [comment]
@MichaelTSS Thanks and I fear @alkiskal has took it :S

**Comment by yosuke-furukawa** [comment]
I am working on 

> Support for SharedArrayBuffer can be added here

**Comment by AdriVanHoudt** [comment]
Taking var -> const in lib/internal/bootstrap_node.js

**Comment by lrlna** [comment]
👋 ; I am in `test-path.js` .

**Comment by quibusus** [comment]
working on unsafe signal warning in lib/internal/process.js

**Comment by alistairjcbrown** [comment]
Working on support for `SharedArrayBuffer` in `lib/util.js`

**Comment by thomasvanlankveld** [comment]
on `test-tls-connect-any-given-socket`

**Comment by delvedor** [comment]
Working on `test-os.js`!

**Comment by akito0107** [comment]
I am working on `test-net-server-address`

**Comment by hohy** [comment]
Working on `test-pipe-file-to-http.js`

**Comment by Thylossus** [comment]
Working con [test-crypto-random.js](https://github.com/nodejs/node/blob/master/test/parallel/test-crypto-random.js)

**Comment by canastro** [comment]
Working on `test-http-agent-destroyed-socket.js`

**Comment by gareth-ellis** [comment]
working on `lib/v8.js, src/node_v8.cc`

**Comment by wzoom** [comment]
DONE working on `test-eval.js`

**Comment by ronaldronson** [comment]
working on test-assert.js

**Comment by RachBLondon** [comment]
working on `test/parallel/test-cluster-disconnect-idle-worker.js`

**Comment by graphicbeacon** [comment]
working on test/parallel/test-async-wrap-post-did-throw.js

**Comment by RachBLondon** [comment]
working on `node/test/parallel/test-cluster-disconnect-unshared-tcp.js`

**Comment by RachBLondon** [comment]
working on `node/test/parallel/test-cluster-disconnect-unshared-udp.js`

**Comment by digitalsadhu** [comment]
working on `test/parallel/test-fs-read.js`

**Comment by JonathanPrince** [comment]
working on `node/test/parallel/test-child-process-send-utf8.js`

**Comment by ilmartyrk** [comment]
working on `test/parallel/test-async-wrap-check-providers.js`
`test/parallel/test-async-wrap-disabled-propagate-parent.js`

**Comment by sejoker** [comment]
working on `test/parallel/test-child-process-exec-env.js`

**Comment by zvictor** [comment]
working on `lib/internal/streams/lazy_transform.js` (referred above as `lib/internal/lazy_transform.js`)

**Comment by AdriVanHoudt** [comment]
doing more var -> const in `/lib/internal/child_process.js`

**Comment by wzoom** [comment]
done working on `test-child-process-disconnect.js`

**Comment by DennisSchwartz** [comment]
Im doing some var to const in test/parallel/test-child-process-stdin.js

**Comment by ilmartyrk** [comment]
For other beginners like me, who want to run single tests try running in console
`/usr/bin/python tools/test.py --mode=release -J \ {path to test}`
for example: 
`/usr/bin/python tools/test.py --mode=release -J \ parallel/test-async-wrap-disabled-propagate-parent`

**Comment by wzoom** [comment]
DONE Working on `test-child-process-cwd.js`

**Comment by bengl** [comment]
Is there a thread to organize this for Austin?

**Comment by addaleax** [comment]
@bengl I don’t think so, so: https://github.com/nodejs/code-and-learn/issues/59

**Comment by Trott** [comment]
Closing because this happened and planning for the next one is over in #59. As always, feel free to re-open or comment if you feel this really shouldn't be closed.

**Comment by AdriVanHoudt** [comment]
@Trott you made a slight typo in Amsterdam ;)

**Comment by hackygolucky** [comment]
There is now! #60
