### ISSUE TITLE
Tel Aviv Nov 20th

### ISSUE THREAD

**Issue by benjamingr** [nodejs/code-and-learn#75]
I'll be onboarding (hopefully) around 8 people in Tel Aviv as a part of an open source event we've been doing monthly in the last few months.

If anyone is around by any chance and wants to help - any help is appreciated :)

**Comment by Trott** [comment]
Only other Collaborator I'm aware of in Israel is @jhamhader.

**Comment by benjamingr** [comment]
@Trott me too - but people travel and I was hoping someone might be around :)

**Comment by Trott** [comment]
> but people travel and I was hoping someone might be around 

Oh, sure, I just was taking the opportunity to ping them by name, that's all. :-D

**Comment by benjamingr** [comment]
Anyone has any interesting ideas for PRs for tomorrow? the good-first-issue tag is a little lacking at the moment :)

**Comment by Trott** [comment]
> the good-first-issue tag is a little lacking at the moment :)

AFAICT, it's always lacking. If something is legitimately a good first issue, someone or multiple someones do it within a day or two, often within an hour or two. Otherwise, it's a good first issue for someone with a very specific set of skills.

Hopefully @MylesBorins wasn't going to use these for C+L Taiwan this week, but there are two tests still using `common.fixturesDir` so replacing that would be tasks for two people. Then a third task (after those first two land) could be to remove `common.fixturesDir` from `test/common/index.js` and `test/common/README.md`?

**Comment by Trott** [comment]
This probably isn't a change for Node.js core but rather a change for tooling around Node.js core, but if that's fine then maybe: Find the tooling for making the changelog and change things that say "semver-major" to "breaking changes" and "semver-minor" to "new features"? Or at least do that for section headings like https://github.com/nodejs/node/blob/master/doc/changelogs/CHANGELOG_V9.md#semver-major if not the individual commits in that section?

**Comment by MylesBorins** [comment]
We use changelog maker for generating changelogs

Seems like that would be where that would need to be implemented Rich

**Comment by MylesBorins** [comment]
Closing as the 20th has already happened!

@benjamingr how'd it go?

**Comment by benjamingr** [comment]
Went pretty well - translated to 5 PRs and people seemed enthusiastic. I'll report back next month and see who showed up again.
