### ISSUE TITLE
Code And Learn at NodeFest 2018

### ISSUE THREAD

**Issue by hiroppy** [nodejs/code-and-learn#92]
[NodeFest2018](https://nodefest.jp/2018/)

I'm sorry that the submission of the issue was delayed.

Today, we'll have a Code-and-Learn event so I think that PR of Code And Learn will be submitted between 15:00 and 17:00. Thanks.

/cc @nodejs/collaborators @addaleax @joyeecheung 

## Mentors

- [x] @hiroppy 
- [x] @ronkorving 
- [x] @Leko 
- [x] @shisama 
- [x] @addaleax 
- [x] @joyeecheung

**Comment by gireeshpunathil** [comment]
@hiroppy - great to know about the event; I am stand by for remote review service!
 - 15.00 Japan time?
 - how many participants expected?
 - what are the assignments you have in mind?

one high level observation from Bangalore code & learn was that new comers benefit a lot of an introductory session on git / github itself, since that is where people find it hard; not necessarily the actual changes. So worthwhile to spend some 30 minutes on git commands as a precursor to the event; just a suggestion. thanks!

**Comment by hiroppy** [comment]
Oops sorry, 

1. 15:00 is JST. UTC is 06:00. 
2. The number of participants is about 30 people.(maybe...)
3. https://github.com/nodejsjp/node-1/issues/1

Thanks for the advice!

**Comment by refack** [comment]
For future reference, it's a good practice to coordinate these events with the BuildWG. This weekend we planned to lock down the CI cluster in preparation for a security release - https://github.com/nodejs/build/issues/1594. Fortunately the lock-down was postponed.

/CC @nodejs/code-and-learn

**Comment by hiroppy** [comment]
Code and Learn has finished successfully. Thanks!
